Utilizando array com matrizes.
Minicurso Python Básico - A Nepomuceno (jun/21)

In [2]:
import numpy as np

In [3]:
#vamos criar a matriz M
a,b,= np.sqrt(2),np.sqrt(3)
M = 1/(np.sqrt(6.))*np.array([ [a,1,b],[-a,2,0],[a,1,-b]])
print(M)

[[ 0.57735027  0.40824829  0.70710678]
 [-0.57735027  0.81649658  0.        ]
 [ 0.57735027  0.40824829 -0.70710678]]


In [4]:
#transposta de M é M.T
r = np.dot(M,M.T)
print(r)

[[ 1.00000000e+00 -4.58633852e-19  4.26642159e-17]
 [-4.58633852e-19  1.00000000e+00 -4.58633852e-19]
 [ 4.26642159e-17 -4.58633852e-19  1.00000000e+00]]


In [5]:
r.diagonal()

array([1., 1., 1.])

In [6]:
#vamos verificar se r é a matriz I (np.eye)
s,_ = r.shape
(np.isclose(r,np.eye(s))).all()

True